replicaCount: 1

image:
  repository: yb2411/pythonweb
  pullPolicy: IfNotPresent
  tag: 7c7e0f192515ad76257470c5ea05b89947dd5624

service:
  type: ClusterIP
  port: 80

resources: {}

config:
  index.html: |
    "<!DOCTYPE html>
    <html>
    <head>
    <title>Hello World</title>
    </head>
    <body>
    <h1>Hello World!</h1>
    </body>
    </html>"
