replicaCount: 1

image:
  repository: yb2411/pythonweb
  pullPolicy: IfNotPresent
  tag: d5e222e8a83d4433ec4294ddf94b4164448825f7

service:
  type: ClusterIP
  port: 80

resources: {}

config:
  index.html: |
    "<!DOCTYPE html>
    <html>
    <head>
    <title>Hello World</title>
    </head>
    <body>
    <h1>Hello World!</h1>
    </body>
    </html>"
