apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-hello-world.fullname" . }}-config
  labels:
    {{- include "nginx-hello-world.labels" . | nindent 4 }}
data:
  index.html: {{ .Values.config.index.html }}
